# Generated by Django 5.2.7 on 2026-04-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymagazine',
            old_name='monthly_price',
            new_name='weekly_price',
        ),
    ]
