# Generated by Django 5.2.7 on 2026-04-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('customer', 'month', 'year')},
        ),
    ]
