# Generated by Django 5.2.7 on 2026-04-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_monthly_price_weeklymagazine_weekly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
