# Generated by Django 5.2.7 on 2026-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bill_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='weekly_magazine_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='weekly_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
