# Generated by Django 5.2.7 on 2026-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bill_weekly_magazine_amount_bill_weekly_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymagazine',
            old_name='monthly_price',
            new_name='weekly_price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='weekly_price',
        ),
        migrations.AddField(
            model_name='bill',
            name='weekly_magazine_amount',
            field=models.FloatField(default=0),
        ),
    ]
