# Generated by Django 5.2.7 on 2026-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bill_is_paid_bill_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('PhonePe', 'PhonePe'), ('GPay', 'GPay'), ('UPI', 'UPI'), ('Bank', 'Bank Transfer')], default='Cash', max_length=20),
        ),
    ]
