# Generated by Django 5.2.7 on 2026-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='additionalpaper',
            name='monthly_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='additionalpaper',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='additional_paper_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='monthly_magazine_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='newspaper_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='weekly_magazine_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custom_additional_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custom_monthly_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custom_newspaper_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custom_weekly_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stop_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymagazine',
            name='monthly_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlymagazine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='monthly_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklymagazine',
            name='monthly_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklymagazine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
