# Generated by Django 5.2.7 on 2026-04-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_monthly_price_weeklymagazine_weekly_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
    ]
